version:  '3.7'

services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - "${MARIADB_PORT}"
    restart: unless-stopped
    networks:
      - back
    volumes:
      - "mariadb_volume:${DB_PATH}"
    environment:
      - DB_PATH = ${DB_PATH}
      - DATABASE_NAME = ${DATABASE_NAME}
      - ADMIN_USERNAME = ${ADMIN_USERNAME}
      - ADMIN_PASSWORD = ${ADMIN_PASSWORD}
      - USERNAME = ${USERNAME}
      - PASSWORD = ${PASSWORD}
    command: ["/usr/bin/mysqld_safe"]
  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "${WP_PORT}:${WP_PORT}"
    depends_on:
      - "mariadb"
    restart: unless-stopped
    volumes:
      - "wordpress_volume:${WP_PATH}"
    networks:
      - front
      - back
    environment:
      - WP_PATH = ${WP_PATH}
      - WP_TITLE = ${WP_TITLE}
      - CONF_FILE_PATH = ${CONF_FILE_PATH}
      - DOMAIN_NAME = ${DOMAIN_NAME}
      - WP_LOCAL_PATH = ${WP_LOCAL_PATH}
      - ADMIN_MAIL = ${ADMIN_MAIL}
      - DB_HOST = ${DB_HOST}
      - EMAIL = ${EMAIL}
      - DATABASE_NAME = ${DATABASE_NAME}
      - ADMIN_USERNAME = ${ADMIN_USERNAME}
      - ADMIN_PASSWORD = ${ADMIN_PASSWORD}
      - USERNAME = ${USERNAME}
      - PASSWORD = ${PASSWORD}
    command: ["php-fpm7.3", "-F"]
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - "wordpress"
    restart: unless-stopped
    volumes:
      - "wordpress_volume:${WP_PATH}"
    networks:
      - front
    environment:
      - NGINX_PORT = ${NGINX_PORT}
    command: ["nginx", "-g", "daemon off;"]

volumes:
  wordpress_volume:
#    driver: "local"
#    driver_opts:
#      o: bind
#      type: "none"
#      device: ${VOLUME_PATH}/wordpress
  mariadb_volume:
#    driver: "local"
#    driver_opts:
#      o: bind
#      type: "none"
#      device: ${VOLUME_PATH}/mariadb

networks:
  front:
    driver: bridge
  back:
    driver: bridge
